### ISSUE TITLE
[Feature Request] Ability to edit outputs or add new ones

### ISSUE THREAD

**Issue by armuell** [AlexNijjar/The-Extractinator#1]
This might already be a planned feature in which this can be ignore. The ability to add items to the output of say cobblestone or adjust the weighting to the default outputs would be great. Additionally being able to add new recipes using any modded block/item as input or output for the extractinator would be amazing.

**Comment by AlexNijjar** [comment]
There is some primitive support for this already. There is an option in the config called “Supported Blocks,” which allows you to add and remove blocks, as well as set their drops and rarity. I want to expand on this feature, though, because it is difficult to understand.

**Comment by armuell** [comment]
Does the current system allow for any modded block/item to be an input/output or only supported mods? I'm able to edit the config and change the drops of but only vanilla items are being added and none of the support mods our in the pack I'm making.

**Comment by AlexNijjar** [comment]
It’s supposed to support other mods, but I have discovered a bug on current versions that prevents that functionality. I’ve now patched it, so it should work on the latest commit. Also, make sure that you add the mod id that you want to support in the “Supported Mods” part of the config.

**Comment by AlexNijjar** [comment]
The mod is now data-driven, so you can add new drops and change recipes with a data pack.
