### ISSUE TITLE
[Suggestion] EMI support

### ISSUE THREAD

**Issue by Pirogiran** [AlexNijjar/The-Extractinator#11]
There some features that EMI support, but not REI. Can you add support for EMI on 1.18.2?
If it's not too difficult, of course.

**Comment by AlexNijjar** [comment]
I don't know about 1.18.2. But it will be in the 1.19.2 version

**Comment by NolanHewitt** [comment]
I'm using the 1.20.1 version for fabric but it seems EMI isn't supported?
