### ISSUE TITLE
[Compatibility]: Re-publish old 1.19.2 mod version for compatibility

### ISSUE THREAD

**Issue by ManuCoding11** [AlexNijjar/The-Extractinator#20]
### Is your feature request related to a problem?

As many servers running the mod still have the old (1.0.0) version installed, I suggest re-uploading it to CurseForge for the sake of compatibility.

### Mod Version

2.0.0

### Mod Loader Version

1.19.2 - 0.14.10

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
There was never an old 1.19.2 version to begin with, the version before this was 1.19.1. Can you try the old 1.19.1 version on 1.19.2? If it works, I'll mark it for 1.19.2

**Comment by ManuCoding11** [comment]
You're right, it was indeed the 1.19.1 version we've been using in our pack. CurseForge detected the new 1.19.2 version as an update and then didn't show the other versions. It actually works for 1.19.2 tho.

I feel really dumb now. -_-

**Comment by AlexNijjar** [comment]
Oh great. I'll update that old version to work with 1.19.2 :)
