### ISSUE TITLE
Resourcelib bug causes incompatibility with Extractinator and Bouncylife for EMI in Multiplayer.

### ISSUE THREAD

**Issue by ConqAra** [AlexNijjar/The-Extractinator#23]
### Bug Description

Issue found here: [https://github.com/emilyploszaj/emi/issues/121](https://github.com/emilyploszaj/emi/issues/121)

It's not that EMI is incompatible nor bouncylife, but when you have these mods together with EMI it causes issues.

From what I gather a bug with resourceful lib causes extractinator to break vanilla recipe sync, and will prevent EMI from loading recipes. I think you should be notified either way just in case.

### How to Reproduce?

Could be a bit weirder to reproduce but essentially in my modpack this is what I had to do:
1. Install Bouncylife
2. Install EMI
3. Install Extractinator
4. Join Multiplayer server that matches modlist with client
5. EMI won't show recipes unless you join a singleplayer world first and then go back to the server.

### Expected Behavior

All 3 mods should work fine together and have EMI load all recipes in multiplayer without any trouble.

### Version

2.0.0

### Mod Loader Version

1.18.2 - 0.14.10

### Mod Loader

Fabric

### Logs or additional context

[https://paste.ee/p/ray3y](https://paste.ee/p/ray3y)

**Comment by emilyploszaj** [comment]
Just as a note, this has nothing to do with EMI, this is a multiplayer recipe sync issue and is present in the recipe book and other recipe viewing mods.

**Comment by AlexNijjar** [comment]
Alright, we managed to fix this and will have an update out soon
