### ISSUE TITLE
[Bug]: Not Working on 1.19.3

### ISSUE THREAD

**Issue by SnowJay2005** [AlexNijjar/The-Extractinator#24]
### Bug Description

I'm sure you're probably already working on an update, but in case you didn't know that 1.19.3 broke the mod, thought I'd let you know

### Version

2.0.1

### Mod Loader Version

1.19.3 - 0.17.8

### Mod Loader

Quilt

**Comment by AlexNijjar** [comment]
Very well aware, 1.19.3 will break almost all 1.19.2 mods as registration was completely changed. A 1.19.3 will be a few months from now, if we even decide to support it and not skip to 1.20

**Comment by AlexNijjar** [comment]
Wait I just realized I was responding to a different repository. My bad. For Extractinator I’ve already updated and am just waiting for it’s dependencies: JEI and Resourcefullib to update

**Comment by SnowJay2005** [comment]
Oh cool, thanks for the quick response
