### ISSUE TITLE
[Feature Request]: List of compatible mods

### ISSUE THREAD

**Issue by rinandstyx** [AlexNijjar/The-Extractinator#25]
### Is your feature request related to a problem?

I looked through your bug report for compatible mods like bewitchment, but i feel like it would be a handy resource, as a modpack developer, to know what mods by default are already hard coded to work.

### Describe alternatives you've considered

Even if you don't want to have it on your main modpage I think it would be nice to have an updated list here or another alternative.

### Mod Version

2.0.1

### Mod Loader Version

1.19.2

**Comment by AlexNijjar** [comment]
in the most recent update, there's not really a set list of supported mods as the drops are now tag-based. This means that for example, any mod's silver ingots will drop. There's a few custom drops for things like Mekanism Osmium and Modern Industrialization Antimony but none of that is hardcoded and can easily be removed by overriding tags in a datapack.
