### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by BamsyTheSergal** [AlexNijjar/The-Extractinator#26]
### Is your feature request related to a problem?

No way to easily add or change individual chances of resources that come out of it

### Solution(s)

in the config area under resourseful, add a way to add new ores/things

### Describe alternatives you've considered

or basically make it so it could use datapacks to add them

### Mod Version

2.0.1

### Mod Loader Version

1.19.2 - 0.14.12

### Mod Loader

Fabric

### Additional context

it would help alot for modpack authors if they wanna use this mod for one of the main sources of resources and what not! c:

**Comment by AlexNijjar** [comment]
data packs can already change them, it's all recipe and tag based. Adding that whole system in the config is way too complicated and causes a lot of issues for both me and the user
