### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by pdoktor** [AlexNijjar/The-Extractinator#27]
### Is your feature request related to a problem?

I'm frustrated that you removed extractinators from subterrestrials and nerfed them completely. I don't care for the new texture either but that is my opinion

### Solution(s)

Please go back and atleast put extractinators in subterrestrials again, that was the main reason of adding that mod to my modpack. It also makes subterrestrials really filled with the same few blocks and rewards when there is no extractinator

### Describe alternatives you've considered

Perhaps you could make the spawn rate of extractinators in subterresterials low, so its not easy to find them but still rewarding nonetheless??

### Mod Version

2.0.1

### Mod Loader Version

1.19.2 fabric 0.14.12

### Mod Loader

Fabric

**Comment by Cyclops3161** [comment]
I totally agree with this post and was meaning to make a similar one myself. This mod is great and I love it dearly, but as it stands right now I just want to get excited when I see the subterrestrial again. The loot tables have been significantly nerfed and most of the items received range from barely useful to things like nether quartz. In conjunction with that the mod requires (in my personal opinion) too much material to be viable in any capacity in comparison to previous versions. The older texture was also a personal favorite of mine but I'm not particularly opposed to the updated version.  In conclusion I hope you take what was said to heart and consider implementing some changes to this mod 

Have a good day

**Comment by AlexNijjar** [comment]
the extractinator is supposed to spawn with the subterrestrial structures. are they not? that would be a bug

as for nerfing the drops, a lot of people were complaining that the drops were way to OP, so I reduced them. You can just increase the drops in the config though; check the lootMultiplier value
