### ISSUE TITLE
[Bug]: Worst config file ever

### ISSUE THREAD

**Issue by yunghemorrho1d** [AlexNijjar/The-Extractinator#28]
### Bug Description

I cant add custom drops because of terrible config file. Is there any way to bring the old one back ?

### Version

0.2.1

### Mod Loader Version

Custom version 1.19.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
What's wrong with the config file? also custom drops are handled through a data pack, not the config

**Comment by yunghemorrho1d** [comment]
That's the file i got.

![Screenshot_2](https://user-images.githubusercontent.com/123318222/214053453-1b5e65f8-e781-4d55-a360-b0784826635a.jpg).
 Where can i find data pack for this mod ?

**Comment by AlexNijjar** [comment]
what makes that the worst config file ever? looks normal to me.

you’d have to make your own datapack if you want to add custom drops. if you just want to increase the drop amount, you can increase the loot multiplier value

**Comment by yunghemorrho1d** [comment]
> what makes that the worst config file ever? looks normal to me.
> 
> you’d have to make your own datapack if you want to add custom drops. if you just want to increase the drop amount, you can increase the loot multiplier value

Is there any way to get the old version of this mod with normal cofiguration file? Because i want to add custom drops like i did on the 1.18 version

**Comment by AlexNijjar** [comment]
i believe the configurable drops were removed nearly a year ago as it was very difficult to maintain in that config. what version are you using?

**Comment by yunghemorrho1d** [comment]
> i believe the configurable drops were removed nearly a year ago as it was very difficult to maintain in that config. what version are you using?

Currently im using Fabric 1.19.2. Version of your mod is 2.0.0. On my previous version 1.18.1 i used 1.02 and after upgraded to 1.05

**Comment by yunghemorrho1d** [comment]
> i believe the configurable drops were removed nearly a year ago as it was very difficult to maintain in that config. what version are you using?

Also i used ModMenu to add my custom drops to Extractinator

**Comment by AlexNijjar** [comment]
that old way won’t be coming back, at least not how it was before. i might add a simple blacklist or something but that old system was way to complicated to maintain and had poor mod compat. show me your old config file with the old drops. i can make you a quick datapack if you want

**Comment by yunghemorrho1d** [comment]
> that old way won’t be coming back, at least not how it was before. i might add a simple blacklist or something but that old system was way to complicated to maintain and had poor mod compat. show me your old config file with the old drops. i can make you a quick datapack if you want

Thats one of the reason why i created this post. I can't find any version of your mod in my 4 foulders. It literaly dissapeared

**Comment by yunghemorrho1d** [comment]
Is there any way to make it work faster ? It's 20x slower than previous one
