### ISSUE TITLE
[Bug]: No longer mines compatible blocks above it.

### ISSUE THREAD

**Issue by TookYourToast** [AlexNijjar/The-Extractinator#34]
### Bug Description

I'm unsure if this was intentionally removed or not but I very much enjoyed the feature that I do believe is still in 1.19.2 version but no longer works in 1.19.4. Basically, if I placed a block above (cobblestone) the extractinator, it would mine the block and there was a chance ore would drop. This no longer works.

### How to Reproduce?

Place extractinator, shift right click block on top or other method of placing compatible block (i.e. cobblestone) above extractinator.

### Expected Behavior

Basically, if I placed a block above (cobblestone) the extractinator, it would mine the block and there was a chance or would drop.

### Version

extractinator-forge-1.19.4-2.1.0.jar

### Mod Loader Version

Forge - 45.0.49 (1.19.4)

### Mod Loader

Forge

### Logs or additional context

I even tried creating a new mod profile on Forge 45.0.50 for 1.19.4. No optifine and as the only mod other than dependencies. I love your mod and don't think the lack of this feature would make me stray away from it. But I do miss it!

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Was accidentally removed. Fixed in 1.20
