### ISSUE TITLE
[Feature Request]: Allow disabling additional blocks

### ISSUE THREAD

**Issue by Dekamir** [AlexNijjar/The-Extractinator#38]
### Is your feature request related to a problem?

Blocks added by this mod (currently Silt and Slush) are only there to use for extracting.
They don't have any other reason to exist. They're not used in anything else, including their non-existent variants.

Also, some other mods already add these. For example, Twigs already adds Silt, with all its respective variants.

Allowing disabling this will alleviate duplicate block problems in modpack instances.

### Solution(s)

Allow a config to disable additional blocks. This config should completely unregister the block, not just stop its world generation (it's the player's responsibility to manage missing blocks if they disable it after world generation).

### Describe alternatives you've considered

Just remove the blocks altogether. This mod does not need to add these. I know it's from Terraria, but Terraria is a completely different game.
You may need to warn existent players, though.
Those blocks can be separated as another mod to avoid missing blocks.

### Mod Version

2.0.1

### Mod Loader Version

0.19.21

### Mod Loader

Fabric

### Additional context

_Image containing Extractinator's Silt and Twigs' Silt and its variants._
![image](https://github.com/AlexNijjar/Extractinator/assets/28929300/f38bcb24-38f2-4617-ad46-ee5ee3486443)

**Comment by hallool** [comment]
i looked trough the jar file and found u coould remove silt/slush from the jei and rei folders inside the jar file so they at least dont show up in jei/rei although im not sure if that works with fabrik the same way as with forge

and found world spawn for those two could disable it by changing 1-2 numbers, not sure if it breaks stuff i didnt make this mod

**Comment by AlexNijjar** [comment]
I'd rather not completely deregister them – there's no point in doing that and I'd rather play it safe. However, I can add a config for fabric specifically to disable them from worldgen. Forge is already configurable via datapack.

**Comment by hallool** [comment]
> I'd rather not completely deregister them – there's no point in doing that and I'd rather play it safe. However, I can add a config for fabric specifically to disable them from worldgen. Forge is already configurable via datapack.

how do i doo that i mean datapack edit  if i look in world datapack folder there is nothing init  i dont know how to find the datapack to change stuff  i can only find  extractinator.jsonc  
![grafik](https://github.com/AlexNijjar/Extractinator/assets/48066058/371b39a2-7bcc-4fdc-b691-ec3d1ca3e4f1)
 in config folder

**Comment by AlexNijjar** [comment]
You'll want to remove these 2 files for forge

https://github.com/AlexNijjar/Extractinator/blob/1.20.x/forge/src/main/resources/data/extractinator/forge/biome_modifier/add_silt.json

https://github.com/AlexNijjar/Extractinator/blob/1.20.x/forge/src/main/resources/data/extractinator/forge/biome_modifier/add_slush.json

you can use something like kubejs to remove them

https://www.curseforge.com/minecraft/mc-mods/kubejs
 https://discord.gg/lat
