### ISSUE TITLE
Add modded hoppers/pipes for output

### ISSUE THREAD

**Issue by TristanKing0** [AlexNijjar/The-Extractinator#4]
Using a hopper from a mod such as Tokenable Furnaces doesn't work for the output, the resources get stuck on top of the Extractinator.

**Comment by AlexNijjar** [comment]
Fixed it. The Extractinator should be able to insert into any hopper inventory now. The patch will be available when 1.18.2 comes out.

**Comment by TristanKing0** [comment]
So this fix wont be available to use in 1.18.1 modpacks?

**Comment by AlexNijjar** [comment]
Probably not. It's not a significant issue, so I don't see a point in creating an entire update for it.

**Comment by TristanKing0** [comment]
The main issue is that your Extractinator can produce resources so fast that it overwhelms vanilla hoppers, so modded hoppers are necessary or it overflows. A significant issue for automation.

**Comment by AlexNijjar** [comment]
I've decided to make one more 1.18.1 release that fixes this issue.
