### ISSUE TITLE
[Feature Request]: There are no instructions, rendering the mod useless

### ISSUE THREAD

**Issue by arconom** [AlexNijjar/The-Extractinator#43]
### Is your feature request related to a problem?

The mod doesn't describe how to use it.

### Mod Version

Sky Fabrication 3

### Mod Loader Version

Sky Fabrication 3

**Comment by AlexNijjar** [comment]
You right-click it with a block. I don't think it's a very hard concept to grasp.

**Comment by cerrita** [comment]
I think they're looking for info on how to craft the extractinator in the first place, which I'm also looking for. I had to use the /give command just to get started.

**Comment by AlexNijjar** [comment]
see #44

**Comment by arconom** [comment]
More specifically, the mod should describe which sides are able to receive input.  It seems as though the top is not able to receive inputs.  Probably the bottom as well.
