### ISSUE TITLE
[Feature Request]: How do I actually build the Extractinator? Add it to the docs

### ISSUE THREAD

**Issue by ViniChab** [AlexNijjar/The-Extractinator#44]
### Is your feature request related to a problem?

No;

### Solution(s)

Add the recipe for building the Extractinator to the docs, I have no idea how to build it on survival;

### Mod Version

2.1.0

### Mod Loader Version

1.19.4

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
<img width="561" alt="Screenshot 2023-11-12 at 5 31 15 PM" src="https://github.com/AlexNijjar/Extractinator/assets/61668546/ed3cfef6-4887-4bea-adb8-92352bde2cf1">

You should be using JEI/REI/EMI. I'll add it to the readme as well.
