### ISSUE TITLE
[Feature Request] [Forge 1.20.1]: Ability to configure the mod

### ISSUE THREAD

**Issue by vizthex123** [AlexNijjar/The-Extractinator#47]
### Is your feature request related to a problem?

As the title says, being able to configure the mod (accepted blocks, what each block drops, the droprate for items, speed of the machine, etc.) would be great.

### Mod Version

2.3.0

### Mod Loader Version

47.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
You can. you can use a datapack to modify recipes/tags. and the speed can be changed in the config: `extractTicks`

https://github.com/AlexNijjar/Extractinator/tree/1.20.x/common/src/main/resources/data/extractinator/tags/items
https://github.com/AlexNijjar/Extractinator/tree/1.20.x/common/src/main/resources/data/extractinator/recipes/extractinating

**Comment by vizthex123** [comment]
There's no link to any sort of docs (nor mention of it on the CF page), so i thought it wasn't configurable. Would be nice if that got fixed.
