### ISSUE TITLE
Datapacks unable to overwrite existing supported_blocks

### ISSUE THREAD

**Issue by BillBodkin** [AlexNijjar/The-Extractinator#7]
When trying to create a data-pack to overwrite cobblestone, it continues to use the mod's default settings.
I believe this is because in ResourceData, the new datapack's version is being added to the supportedBlocks list instead of replacing the existing value.

From my testing it seems the datapack version is always loaded after the mod's one. So I guess its just a case of over-wiring the old value when another one is loaded afterwards.

Havant tested the output tiers one yet.

**Comment by AlexNijjar** [comment]
Fixed
