### ISSUE TITLE
Automation Not Working

### ISSUE THREAD

**Issue by KintsugiKitten** [AlexNijjar/The-Extractinator#8]
On the Modrinth page, the description says that it can be automated with hoppers. I've  attempted to do this, but instead of going into the hopper beneath it, the products fly into the air. I'm using Minecraft version 1.19 and mod version 1.0.9. I'd suggest noting the issue on Modrinth until it's corrected. Thanks!

**Comment by AlexNijjar** [comment]
Thanks for reporting; I’ll make a hot fix immediately.

**Comment by AlexNijjar** [comment]
Fixed

**Comment by rinandstyx** [comment]
I am on 1.19.2 and having this same issue, is automation an intended feature?
