### ISSUE TITLE
Cant create loot table

### ISSUE THREAD

**Issue by AlphaLucy** [AlexNijjar/The-Extractinator#9]
I cant use the machine it doesnt work and it says this
![Screenshot_1](https://user-images.githubusercontent.com/64836458/173128134-92c39eac-6693-4ca9-bbea-3500ecc258ab.png)

**Comment by AlexNijjar** [comment]
What version of the mod are you currently using?
What is your modlist?
Are you on a local world or a server?

**Comment by AlphaLucy** [comment]
-1.0.8/1.0.7
-I made it myself so i cant list the mods but I have some of the supported
mods
-I m hosting a server for my friends so yes server

**Comment by AlphaLucy** [comment]
1.0.8/1.0.7*
